services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: poetry run python main.py
    restart: unless-stopped